### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nstandif** [sverchdotgov/zipcode-to-lat-long#1]
There should be a license attributed to the source code. Without a license, the source code assumes all rights to the owner.

**Comment by sverchdotgov** [comment]
Added the MIT license: https://github.com/sverchdotgov/zipcode-to-lat-long/commit/679815b1779627cb04dca10aa184d03218f03d97 I'm the only author.

Thanks for the suggestion, random internet person @nstandif!
